---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: hook-deletion
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hook-deletion
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - verbs:
      - delete
    apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hook-deletion
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
  - kind: ServiceAccount
    name: hook-deletion
    namespace: openshift-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hook-deletion
---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: hook-deletion
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - name: ose
              image: registry.redhat.io/openshift4/ose-cli:v4.14
              command:
                - /bin/bash
                - -c
                - oc delete validatingwebhookconfigurations sre-node-validation-osd; exit 0
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: OnFailure
          serviceAccount: hook-deletion
          serviceAccountName: hook-deletion
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
