---
apiVersion: forklift.konveyor.io/v1beta1
kind: ForkliftController
metadata:
  name: forklift-controller
  namespace: openshift-mtv
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  feature_must_gather_api: 'true'
  feature_ui_plugin: 'true'
  feature_validation: 'true'
  feature_volume_populator: 'true'
