---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mtv-operator
  namespace: openshift-mtv
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: release-v2.5
  installPlanApproval: Automatic
  name: mtv-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: mtv-operator.v2.5.5
